#!/bin/sh
# Copy one program's device-side modules to the board and restart it.
# main.py autoruns at power-on, so *which* program gets copied to main.py is a
# deploy-time decision -- there is no runtime chooser and nothing on the board
# remembers the last choice.
#
#   ./tools/deploy.sh              # Magic 8-Ball (src/main.py)   -- the default
#   ./tools/deploy.sh 8ball        # the same, said out loud
#   ./tools/deploy.sh eliza        # push-to-talk ELIZA (src/talk.py)
#   ./tools/deploy.sh record       # just the enrolment capture path; leaves
#                                  # main.py and the running program alone
#   PORT=/dev/cu.usbmodem1101 ./tools/deploy.sh eliza
#
# Both programs share board/epaper/magic8/es8311/audio_pio_mpy, and the modules
# of whichever program is not running are simply left behind on the filesystem:
# they cost flash, which is plentiful, and nothing imports them.
set -eu

PORT="${PORT:-/dev/cu.usbmodem101}"
PROGRAM="${1:-8ball}"
cd "$(dirname "$0")/.."

# Where tools/record_templates.py puts the enrolled templates, and it is src/
# rather than the repo root on purpose: --format bin writes *two* files, the
# blob and the templates.py loader that reads it, and the loader has to be in
# src/ for the module loop below to copy it. Keeping the pair together means
# `record_templates.py` with no arguments produces something this script can
# deploy with no arguments. tools/test_templates.py asserts this exact path
# against the real emit(), because the two ends used to disagree silently: the
# loader shipped, the blob did not, and the board degraded to the no-keyword
# path looking merely like a shy recogniser.
TEMPLATE_BLOB="src/templates.bin"

# The CNN spotter's two data files. `si_real` is the model that ships: it is the
# one trained on the real-speaker corpus, and its classes are the family nouns
# (mother, father, wife) that ELIZA gets the most out of echoing. `si_am` covers
# the emotional words instead and has never been converted to a .tmdl; if it
# ever is, this is the one line to change.
#
# Measured through this exact path on 10 real takes and 12 real negatives:
# precision 1.000, recall 0.600. See docs/cnn-on-device.md.
CNN_MODEL="${CNN_MODEL:-models/si_real.tmdl}"
CNN_MODULE="${CNN_MODULE:-vendor/emlearn_cnn_int8.mpy}"

SHARED="board epaper es8311 audio_pio_mpy magic8"

case "$PROGRAM" in
    8ball|magic8|"")
        MODULES="$SHARED sounds shake"
        ENTRY="src/main.py"
        CLIPS=1
        READY="Press POWER, BOOTSEL, or tap the screen."
        ;;
    eliza|talk)
        # templates.bin is data, not code: a 70 KB blob of packed statics that
        # templates.py reads with readinto() into one pre-allocated buffer. Same
        # shape as the 8-Ball's clips, and copied the same way below -- but from
        # src/, not from the repo root, because tools/record_templates.py writes
        # the blob and its loader side by side into src/ and the loader has to
        # land there for the module loop below to find it. See TEMPLATE_BLOB.
        # magic8 comes along for wrap() and _text_scaled(). Modules still being
        # written elsewhere are listed anyway and skipped if absent, so this
        # list doubles as the record of what the program expects to find:
        # `templates` (the enrolled words) does not exist until somebody has run
        # tools/record_templates.py, and talk.py degrades without it.
        # `speech_tables` is generated by tools/mfcc.py --emit-tables.
        #
        # `speech_fixtures` is a diagnostic, not a runtime module -- nothing in
        # the program imports it. It ships (54 KB, on a 15 MB filesystem) so that
        # speech_probe section (h) can prove the front end bit-identical on a
        # board that is merely deployed, without mounting src/. That check is
        # the only one the host suite cannot do, and it wants to be available
        # after a firmware change, not only at the bench.
        MODULES="$SHARED listen vad screen record_stream vocab eliza eliza_rules speech_tables spotter speech_fixtures templates si_patch si_spot"
        ENTRY="src/talk.py"
        CLIPS=0
        READY="Hold the screen or POWER, speak, then let go."
        ;;
    record)
        # Enrolment only: tools/pull_recording.py drives record_stream over the
        # REPL. Deliberately does not touch main.py or reset the board -- you
        # may be enrolling against whichever program is already installed.
        MODULES="board es8311 audio_pio_mpy listen record_stream"
        ENTRY=""
        CLIPS=0
        READY="Now run: uvx --from pyserial python tools/pull_recording.py"
        ;;
    *)
        echo "unknown program '$PROGRAM' (try: 8ball, eliza, record)" >&2
        exit 2
        ;;
esac

echo "deploying $PROGRAM to $PORT"

# One file per invocation: mpremote's multi-file cp is fussy about argument form.
for module in $MODULES; do
    if [ ! -f "src/${module}.py" ]; then
        # Not fatal: a module still being written by someone else should not
        # block deploying everything that does exist. The program's own
        # defensive import is what has to cope on the device.
        echo "  !! src/${module}.py missing - skipped"
        continue
    fi
    echo "  -> ${module}.py"
    uvx --quiet mpremote connect "$PORT" cp "src/${module}.py" ":${module}.py"
done

# Data blobs. templates.bin is the enrolled word templates; the .raw clips are
# the 8-Ball's sampled sounds. Only copied when missing or changed would be
# nicer, but mpremote has no sync.
if [ "$PROGRAM" = "eliza" ] || [ "$PROGRAM" = "talk" ]; then
    if [ -f "$TEMPLATE_BLOB" ]; then
        echo "  -> templates.bin"
        uvx --quiet mpremote connect "$PORT" cp "$TEMPLATE_BLOB" ":templates.bin"
    else
        echo "  !! $TEMPLATE_BLOB missing - the spotter will have nothing to match"
        echo "     Build it with tools/record_templates.py after enrolling."
        echo "     For the FIRST run on hardware use --pack full: it needs no"
        echo "     on-device expansion pass, so a recogniser that misbehaves has"
        echo "     one fewer untested cause. Same RAM, 140 KB of flash not 70."
    fi
fi

# The CNN. `si_spot` asks for these two and degrades to DOCTOR's no-keyword path
# without them, so a missing model is a warning and not a failure -- but a model
# that is *present and wrong* is worse than one that is absent, which is why the
# check below is fatal rather than advisory.
#
# `tools/tmdl_info.py` refuses four things TinyMaix will otherwise do silently,
# and one of them was confirmed on this board: an unpadded model overran its
# heap allocation by 1164 bytes during a single inference and raised nothing.
# See docs/cnn-on-device.md.
if [ "$PROGRAM" = "eliza" ] || [ "$PROGRAM" = "talk" ]; then
    if [ -f "$CNN_MODULE" ]; then
        echo "  -> $(basename "$CNN_MODULE")"
        uvx --quiet mpremote connect "$PORT" cp "$CNN_MODULE" ":$(basename "$CNN_MODULE")"
    else
        echo "  !! $CNN_MODULE missing - no CNN spotter; every turn deflects"
        echo "     Fetch it on the Mac (the board has no networking):"
        echo "     curl -O https://emlearn.github.io/emlearn-micropython/builds/latest/armv7emsp_6.3/emlearn_cnn_int8.mpy"
    fi

    if [ -f "$CNN_MODEL" ]; then
        if python3 tools/tmdl_info.py "$CNN_MODEL" > /dev/null 2>&1; then
            echo "  -> si_model.tmdl (from $CNN_MODEL)"
            uvx --quiet mpremote connect "$PORT" cp "$CNN_MODEL" ":si_model.tmdl"
        else
            echo "  !! $CNN_MODEL FAILS tools/tmdl_info.py - refusing to deploy it" >&2
            python3 tools/tmdl_info.py "$CNN_MODEL" >&2
            exit 3
        fi
    else
        echo "  !! $CNN_MODEL missing - no CNN spotter; every turn deflects"
    fi
fi

if [ "$CLIPS" = "1" ]; then
    for clip in clips/*.raw; do
        [ -e "$clip" ] || continue
        echo "  -> $(basename "$clip")"
        uvx --quiet mpremote connect "$PORT" cp "$clip" ":$(basename "$clip")"
    done
fi

if [ -n "$ENTRY" ]; then
    echo "  -> main.py (from $ENTRY)"
    uvx --quiet mpremote connect "$PORT" cp "$ENTRY" ":main.py"

    echo "resetting"
    uvx --quiet mpremote connect "$PORT" reset
fi

echo "done. $READY"
