#!/bin/sh
# Copy one program's device-side modules to the board and restart it.
# main.py autoruns at power-on, so *which* program gets copied to main.py is a
# deploy-time decision -- there is no runtime chooser and nothing on the board
# remembers the last choice.
#
#   ./tools/deploy.sh              # Magic 8-Ball (src/main.py)   -- the default
#   ./tools/deploy.sh 8ball        # the same, said out loud
#   ./tools/deploy.sh eliza        # push-to-talk ELIZA (src/talk.py)
#   ./tools/deploy.sh record       # just the enrolment capture path; leaves
#                                  # main.py and the running program alone
#   PORT=/dev/cu.usbmodem1101 ./tools/deploy.sh eliza
#
# Both programs share board/epaper/magic8/es8311/audio_pio_mpy, and the modules
# of whichever program is not running are simply left behind on the filesystem:
# they cost flash, which is plentiful, and nothing imports them.
set -eu

PORT="${PORT:-/dev/cu.usbmodem101}"
PROGRAM="${1:-8ball}"
cd "$(dirname "$0")/.."

SHARED="board epaper es8311 audio_pio_mpy magic8"

case "$PROGRAM" in
    8ball|magic8|"")
        MODULES="$SHARED sounds shake"
        ENTRY="src/main.py"
        CLIPS=1
        READY="Press POWER, BOOTSEL, or tap the screen."
        ;;
    eliza|talk)
        # templates.bin is data, not code: a 70 KB blob of packed statics that
        # templates.py reads with readinto() into one pre-allocated buffer. Same
        # shape as the 8-Ball's clips, and copied the same way below.
        # magic8 comes along for wrap() and _text_scaled(). Modules still being
        # written elsewhere are listed anyway and skipped if absent, so this
        # list doubles as the record of what the program expects to find:
        # `spotter` (the MFCC/DTW keyword spotter) and `templates` (the enrolled
        # words) do not exist yet, and talk.py degrades without them.
        # `speech_tables` is generated by tools/mfcc.py --emit-tables.
        #
        # `speech_fixtures` is a diagnostic, not a runtime module -- nothing in
        # the program imports it. It ships (54 KB, on a 3 MB filesystem) so that
        # speech_probe section (h) can prove the front end bit-identical on a
        # board that is merely deployed, without mounting src/. That check is
        # the only one the host suite cannot do, and it wants to be available
        # after a firmware change, not only at the bench.
        MODULES="$SHARED listen vad screen record_stream vocab eliza eliza_rules speech_tables spotter speech_fixtures templates"
        ENTRY="src/talk.py"
        CLIPS=0
        READY="Hold the screen or POWER, speak, then let go."
        ;;
    record)
        # Enrolment only: tools/pull_recording.py drives record_stream over the
        # REPL. Deliberately does not touch main.py or reset the board -- you
        # may be enrolling against whichever program is already installed.
        MODULES="board es8311 audio_pio_mpy listen record_stream"
        ENTRY=""
        CLIPS=0
        READY="Now run: uvx --from pyserial python tools/pull_recording.py"
        ;;
    *)
        echo "unknown program '$PROGRAM' (try: 8ball, eliza, record)" >&2
        exit 2
        ;;
esac

echo "deploying $PROGRAM to $PORT"

# One file per invocation: mpremote's multi-file cp is fussy about argument form.
for module in $MODULES; do
    if [ ! -f "src/${module}.py" ]; then
        # Not fatal: a module still being written by someone else should not
        # block deploying everything that does exist. The program's own
        # defensive import is what has to cope on the device.
        echo "  !! src/${module}.py missing - skipped"
        continue
    fi
    echo "  -> ${module}.py"
    uvx --quiet mpremote connect "$PORT" cp "src/${module}.py" ":${module}.py"
done

# Data blobs. templates.bin is the enrolled word templates; the .raw clips are
# the 8-Ball's sampled sounds. Only copied when missing or changed would be
# nicer, but mpremote has no sync.
if [ "$PROGRAM" = "eliza" ] || [ "$PROGRAM" = "talk" ]; then
    if [ -f "templates.bin" ]; then
        echo "  -> templates.bin"
        uvx --quiet mpremote connect "$PORT" cp "templates.bin" ":templates.bin"
    else
        echo "  !! templates.bin missing - the spotter will have nothing to match"
        echo "     Build it with tools/record_templates.py after enrolling."
        echo "     For the FIRST run on hardware use --pack full: it needs no"
        echo "     on-device expansion pass, so a recogniser that misbehaves has"
        echo "     one fewer untested cause. Same RAM, 140 KB of flash not 70."
    fi
fi

if [ "$CLIPS" = "1" ]; then
    for clip in clips/*.raw; do
        [ -e "$clip" ] || continue
        echo "  -> $(basename "$clip")"
        uvx --quiet mpremote connect "$PORT" cp "$clip" ":$(basename "$clip")"
    done
fi

if [ -n "$ENTRY" ]; then
    echo "  -> main.py (from $ENTRY)"
    uvx --quiet mpremote connect "$PORT" cp "$ENTRY" ":main.py"

    echo "resetting"
    uvx --quiet mpremote connect "$PORT" reset
fi

echo "done. $READY"
