#!/usr/bin/env python3
"""Synthesise a labelled speech corpus with macOS `say`, for offline evaluation.

The device is not the only thing missing during development -- so is a room, a
microphone and the patience to say ANGRY forty times. `say` writes 16 kHz mono
int16 WAV directly (`--data-format=LEI16@16000`), which is exactly the format
the front end wants, so a corpus costs a few seconds instead of an afternoon.

**These numbers are optimistic and it is important to know by how much.** One
TTS voice saying MOTHER twice produces two nearly identical waveforms; a person
saying it twice does not. Speaking rate is varied between sessions and a
recorded-channel model is applied on top (gain, additive noise, a first-order
tilt), which reproduces *session* mismatch but not *articulation* mismatch --
the mumbled vowel, the swallowed final consonant, the day with a cold. Treat
the harness numbers as an upper bound and a way to rank design choices against
each other, not as a prediction of what the board will do. The ranking is what
it is for: which words collide, which threshold is safe, whether c0 helps.

    python3 tools/say_corpus.py corpus/            # build the whole thing
    python3 tools/say_corpus.py corpus/ --voice Daniel

Layout:

    corpus/enrol/<form>.<n>.wav      three per spoken form, one session
    corpus/test/<form>.<n>.wav       four per form, other sessions
    corpus/oov/<slug>.<n>.wav        words that must never fire

No third-party packages.
"""

import array
import math
import os
import subprocess
import sys
import wave

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "src"))
import vocab  # noqa: E402

RATE = 16000

# Speaking rates in words per minute. The enrolment session is one rate; the
# test sessions are others, so template and query never come from the same
# synthesis. Anything outside roughly 140-210 makes `say` audibly artificial.
ENROL_RATES = (175, 178, 172)
TEST_RATES = (150, 165, 190, 205)

LEAD_MS = 400        # silence before the word, so the VAD has a background to
TAIL_MS = 400        # measure; the paper wants 100 ms and this gives margin

# Recorded-channel model, per utterance. Modest on purpose: the ES8311's noise
# floor measured -44 dBFS at gain 0 (docs/hardware.md), and a hand-held board
# 20 cm from a mouth is a quiet, close, dry channel.
NOISE_DBFS = (-46, -40, -34)
GAINS_DB = (-6, -3, 0, 3)
TILTS = (0.0, 0.15, -0.15)   # first-order pre/de-emphasis, models mic response

# Out of vocabulary. This is the population the spotter has to stay silent on,
# so it is not random words: it is what someone actually says to a therapist
# toy. Several are deliberate near-misses -- MOTHER'S, WORKING, SORT OF, KNOW,
# NEVER, ALSO -- because those are the false fires that would hurt.
OOV = (
    "hello", "goodbye", "maybe", "perhaps", "sometimes", "never", "also",
    "know", "though", "another", "other", "brother's", "mother's", "working",
    "worked", "slept", "sleeping", "dreaming", "wanted", "needed", "lovely",
    "money's", "computers", "sadly", "happier", "angrier", "afraid of it",
    "sort of", "of course", "i think so", "i suppose", "not really",
    "tell me more", "why do you ask", "i don't know", "it depends",
    "my family", "my friend", "my boss", "my life", "my head", "my fault",
    "everyone", "nobody", "something", "nothing", "anything", "everything",
    "today", "yesterday", "tomorrow", "tonight", "morning", "evening",
    "school", "college", "doctor", "hospital", "medicine", "therapy",
    "problem", "trouble", "worry", "stress", "pressure", "pain",
    "talk", "talking", "listen", "listening", "understand", "remember",
    "forget", "believe", "feel", "felt", "thought", "wonder",
    "because", "before", "after", "again", "still", "already",
)


# Morphological relatives of keywords. A fire here is not a mistake: answering
# "my mother's house" with "DO YOU OFTEN THINK OF MOTHER" is exactly what
# DOCTOR is supposed to do, and NEEDED is literally in the WANT class already.
# The harness scores these separately from the words that must stay silent,
# because lumping them together makes the front end look worse than it is and
# hides the one collision that actually matters.
OOV_VARIANTS = {
    "mother_s": "mother",
    "brother_s": "brother",
    "money_s": "money",
    "working": "work",
    "worked": "work",
    "slept": "sleep",
    "sleeping": "sleep",
    "dreaming": "dream",
    "wanted": "want",
    "needed": "want",
    "computers": "computer",
    "sadly": "sad",
    "happier": "happy",
    "angrier": "angry",
    "lovely": "love",
    "afraid_of_it": "afraid",
}


# Words that USED to be in the vocabulary and must now stay silent.
#
# This list exists because of a trap worth naming. The corpus is generated by
# enumerating `vocab.FORMS`, so the moment a word is cut from the vocabulary it
# stops being recorded -- and the utterances that prove the spotter stays quiet
# on it vanish from the test set at exactly the moment they start mattering.
# The harness would go on reporting precision 1.000 while no longer testing the
# thing the cut was made for.
#
# Deriving a test set from the system under test is right until the thing being
# tested is the system's *absence* of something. So retired words are named
# here explicitly and generated into the out-of-vocabulary set, permanently.
#
# NO went because it is a homophone of KNOW (see src/vocab.py). WANT and NEED
# went because DOCTOR's `(* WANT NEED)` rule provably never fires -- the
# possessive rules outrank it every time.
RETIRED = ("no", "want", "need")


def say_wav(text, path, voice, rate):
    subprocess.run(["say", "-v", voice, "-r", str(rate),
                    "--data-format=LEI16@16000", "--file-format=WAVE",
                    "-o", path, text], check=True)


def read_wav(path):
    with wave.open(path, "rb") as w:
        return array.array("h", w.readframes(w.getnframes()))


def write_wav(path, samples):
    with wave.open(path, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(samples.tobytes())


class Rng(object):
    """A tiny LCG, so a corpus is reproducible from its seed alone. Nothing
    here needs statistical quality; it needs to be the same twice."""

    def __init__(self, seed):
        self.s = seed & 0x7FFFFFFF or 1

    def next(self):
        self.s = (1103515245 * self.s + 12345) & 0x7FFFFFFF
        return self.s

    def gauss_ish(self, scale):
        # Sum of three uniforms: close enough to Gaussian for a noise floor,
        # and it needs no log or sqrt.
        total = 0
        for _ in range(3):
            total += (self.next() >> 8) % 2001 - 1000
        return total * scale // 3000

    def pick(self, seq):
        return seq[self.next() % len(seq)]


def channel(samples, rng, noise_dbfs, gain_db, tilt):
    """Gain, first-order tilt, additive noise, and silence either end."""
    gain_q15 = int(round(32768 * (10.0 ** (gain_db / 20.0))))
    noise_amp = int(32767 * (10.0 ** (noise_dbfs / 20.0)))
    tilt_q15 = int(round(tilt * 32768))

    lead = LEAD_MS * RATE // 1000
    tail = TAIL_MS * RATE // 1000
    out = array.array("h", bytes(2 * (lead + len(samples) + tail)))

    prev = 0
    for i in range(len(out)):
        if lead <= i < lead + len(samples):
            x = samples[i - lead]
        else:
            x = 0
        y = (x * gain_q15) >> 15
        y -= (tilt_q15 * prev) >> 15
        prev = x
        y += rng.gauss_ish(noise_amp)
        out[i] = max(-32768, min(32767, y))
    return out


def slug(text):
    return "".join(c if c.isalnum() else "_" for c in text)


def build(root, voice, seed):
    rng = Rng(seed)
    counts = {}
    for sub in ("enrol", "test", "oov"):
        os.makedirs(os.path.join(root, sub), exist_ok=True)
    raw = os.path.join(root, "_raw.wav")

    def emit(sub, name, text, rate, n):
        say_wav(text, raw, voice, rate)
        clean = read_wav(raw)
        noisy = channel(clean, rng, rng.pick(NOISE_DBFS), rng.pick(GAINS_DB),
                        rng.pick(TILTS))
        write_wav(os.path.join(root, sub, "%s.%d.wav" % (name, n)), noisy)
        counts[sub] = counts.get(sub, 0) + 1

    for form in vocab.FORMS:
        for n, rate in enumerate(ENROL_RATES):
            emit("enrol", form, form, rate, n)
        for n, rate in enumerate(TEST_RATES):
            emit("test", form, form, rate, n)

    for text in OOV:
        for n, rate in enumerate(TEST_RATES[:2]):
            emit("oov", slug(text), text, rate, n)

    # Retired words get the full set of test rates, not the two the rest of the
    # out-of-vocabulary set gets: they were chosen for the vocabulary once, so
    # they are the words most likely to false-fire, and they are worth more
    # evidence than an arbitrary noun is.
    for text in RETIRED:
        for n, rate in enumerate(TEST_RATES):
            emit("oov", slug(text), text, rate, n)

    os.remove(raw)
    return counts


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    root = argv[1]
    voice = "Samantha"
    seed = 20260817
    for i, a in enumerate(argv):
        if a == "--voice":
            voice = argv[i + 1]
        elif a == "--seed":
            seed = int(argv[i + 1])
    counts = build(root, voice, seed)
    print("voice %s, seed %d -> %s" % (voice, seed, root))
    for sub in sorted(counts):
        print("  %-6s %4d utterances" % (sub, counts[sub]))
    print("  %d spoken forms in %d classes, plus %d retired words (%s)"
          % (len(vocab.FORMS), len(vocab.VOCAB), len(RETIRED),
             ", ".join(RETIRED)))
    still_live = [w for w in RETIRED if vocab.label_of(w) is not None]
    if still_live:
        print("  WARNING: %s are in RETIRED but still in the vocabulary"
              % ", ".join(still_live))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
