"""On-device checks for the ADPCM decoder and the streaming playback path.

    PORT=/dev/cu.usbmodem1401 ./tools/deploy.sh eliza
    uvx mpremote connect $PORT run tools/voice_probe.py

Deploy first and then plain `run` -- **not** `mount src`. Sections (a) and (c)
read files off the device's own filesystem (`voice.pak`, and the fixture
modules), and a mount replaces that filesystem with the host directory, where
none of them are. The probe would report "no usable voice.pak" on a board that
has one.

Three sections here, each independently guarded so a board without `voice.pak`
still gets the arithmetic ones, and a fourth that deliberately is not. Nothing
here writes to flash.

  a. **Does the viper decoder agree with the host, on this chip?** The host
     suite proves the decoder matches `tools/voice_pak.py`'s reference given
     unbounded integers. `@micropython.viper`'s `int` is a 32-bit machine word
     that wraps **silently**, so that proof does not carry to the board. This
     runs `src/voice_fixtures.py`, whose expected values came from the
     reference, through the decoder that actually ships.
  b. **How fast is it?** Playback needs 16000 samples a second sustained; the
     question is the margin, because the decode has to finish inside the time
     it takes the DMA to drain the other half.
  c. **How wide is the DMA re-arm gap?** This is the one real risk in the
     streaming design. When a half finishes, the PIO's TX FIFO holds 8 words --
     500 us at 16 kHz -- and if the next DMA is not armed inside that, the state
     machine stalls at its `pull()`, DOUT holds its last level, and there is a
     tick at every boundary. Roughly one boundary a second, so it would be
     unmissable and unlocatable.
  d. **Does a clip sound right?** Deliberately NOT run by this file. Per
     CLAUDE.md it is the only check whose result means anything about what a
     person hears -- (a) through (c) all pass on a board whose speaker is
     disconnected -- and it is the only one that needs a human primed and
     listening at the moment it happens, rather than reading a log afterwards.
     So it is a separate act, run when someone is ready:

         uvx mpremote connect $PORT exec "
         import board, listen
         i2c = board.bus()
         r = listen.Recorder()
         r.bind_voice()
         r.speak(i2c, b'ff7a366a')
         print(r.play_boundaries, r.play_gap_us)
         "

     (`ff7a366a` is 'Tell me more about your family.' -- the sentence every F0
     figure in docs/speech-voice.md was measured on, so a surprise there is a
     surprise against a known number.)

Read the results the way CLAUDE.md says to read anything audio: a decode that
raises no exception proves the arithmetic ran, not that the codec was fed. The
numbers that matter are the fixture agreement in (a) and the measured gap in
(c); everything else is a precondition for those meaning anything.
"""

import gc
import sys
import time
from array import array

from machine import I2C, Pin  # noqa: F401 -- Pin via board

sys.path.insert(0, "/")

FAILED = []


def note(ok, what, detail=""):
    if not ok:
        FAILED.append(what)
    print("   %s %s%s" % ("ok  " if ok else "FAIL", what,
                          ("  -- " + detail) if detail else ""))


def section(letter, title):
    print()
    print("(%s) %s" % (letter, title))


# --- (a) the fixtures ------------------------------------------------------

def check_fixtures():
    section("a", "viper decoder against the host's expected values")
    try:
        import adpcm
    except ImportError as exc:
        print("   skipped: %s" % exc)
        return

    print("   decoder: %s" % ("viper" if adpcm.VIPER else "BYTECODE FALLBACK"))
    if not adpcm.VIPER:
        # Not a failure of correctness, but it is the failure this section
        # exists next to: the plain decoder is right and far too slow, and
        # nothing else on the board would ever say so.
        note(False, "the viper decoder compiled",
             "running the portable path; section (b) will show the cost")

    _check_vectors(adpcm)
    _check_whole_clips(adpcm)


def _check_vectors(adpcm):
    """`src/voice_vectors.py` -- the encoder's vectors, nibble-level and real.

    Generated by `tools/voice_pak.py --fixture-module`. These take the
    arguments `decode_into` takes, so a disagreement is in the decode loop and
    nowhere else, and they carry three clips of real rendered speech where a
    nibble-order or shift mistake shows up as audio rather than as arithmetic.
    """
    try:
        import voice_vectors as vec
    except ImportError as exc:
        print("   voice_vectors: skipped (%s)" % exc)
        return
    if vec.FORMAT != adpcm.FORMAT:
        note(False, "voice_vectors matches the decoder's format",
             "%d vs %d" % (vec.FORMAT, adpcm.FORMAT))
        return

    for case in vec.CASES:
        name, _why, predictor, index, nibbles, n_nibbles, head, tail, want = case
        gc.collect()
        try:
            out = array("h", bytes(4 * n_nibbles))
            state = adpcm.new_state(predictor, index)
            adpcm.decode_into(nibbles, 0, n_nibbles, out, 0, state)
            got = [out[2 * i] for i in range(n_nibbles)]
        except Exception as exc:  # noqa: BLE001
            note(False, "vector %-20s decoded" % name,
                 "%s: %s" % (type(exc).__name__, exc))
            continue
        got_sum = vec.checksum(got)
        if got_sum != want:
            # Head and tail are here precisely so a mismatch says *where*.
            note(False, "vector %-20s" % name,
                 "checksum %d vs %d; head diverges at %s"
                 % (got_sum, want, _first_diff(head, got, min(vec.EDGE,
                                                              n_nibbles))))
        else:
            note(True, "vector %-20s (%d nibbles)" % (name, n_nibbles))
        del out

    for clip in getattr(vec, "CLIPS", ()):
        clip_hex, _why, text, blob, n_samples, head, tail, want = clip
        gc.collect()
        try:
            out = array("h", bytes(4 * n_samples))
            got = _decode_blob(adpcm, blob, out, n_samples)
        except Exception as exc:  # noqa: BLE001
            note(False, "clip %s decoded" % clip_hex,
                 "%s: %s" % (type(exc).__name__, exc))
            continue
        got_sum = vec.checksum(got)
        note(got_sum == want,
             "clip %s (%d samples of real speech) %r"
             % (clip_hex, n_samples, text[:28]),
             "" if got_sum == want else "checksum %d vs %d; head diverges at %s"
             % (got_sum, want, _first_diff(head, got, vec.EDGE)))
        del out


def _check_whole_clips(adpcm):
    """`src/voice_fixtures.py` -- the encoder's loose binary fixtures.

    Generated by `tools/test_adpcm.py --emit-fixtures`. Complementary to the
    vectors above: whole clips including the header, the degenerate lengths
    (empty, one sample, an odd count with a dangling nibble) and both
    saturation rails.
    """
    try:
        import voice_fixtures as fx
    except ImportError as exc:
        print("   voice_fixtures: skipped (%s)" % exc)
        return
    if fx.FORMAT != adpcm.FORMAT:
        note(False, "voice_fixtures matches the decoder's format",
             "%d vs %d" % (fx.FORMAT, adpcm.FORMAT))
        return

    for case in fx.CASES:
        name, _why, blob, expected, n_samples, want_sum = case
        gc.collect()
        try:
            out = array("h", bytes(4 * max(n_samples, 1)))
            got = _decode_blob(adpcm, blob, out, n_samples)
        except Exception as exc:  # noqa: BLE001
            note(False, "%-14s decoded" % name,
                 "%s: %s" % (type(exc).__name__, exc))
            continue
        if len(got) != n_samples:
            note(False, "%-14s length" % name,
                 "%d samples, expected %d" % (len(got), n_samples))
            continue
        if expected is not None:
            # Byte for byte where the fixture carries the samples: a checksum
            # that happens to collide is unlikely and a checksum that hides
            # *where* a decoder diverged is certain.
            raw = bytes(expected)
            same = all(_le16(raw, i) == got[i] for i in range(n_samples))
            note(same, "%-14s (%d samples, byte for byte)" % (name, n_samples),
                 "" if same else "first difference at %d"
                 % _first_diff(raw, got, n_samples))
        else:
            got_sum = fx.checksum(got)
            note(got_sum == want_sum,
                 "%-14s (%d samples, checksum)" % (name, n_samples),
                 "" if got_sum == want_sum else "%d vs %d" % (got_sum, want_sum))
        del out


def _decode_blob(adpcm, blob, out, n_samples):
    """Decode a whole fixture blob into `out`, returning it as a list."""
    if not n_samples:
        return []
    predictor = blob[4] | (blob[5] << 8)
    if predictor > 32767:
        predictor -= 65536
    index = blob[6]
    adpcm.emit_sample(out, 0, predictor)
    nibs = n_samples - 1
    if nibs:
        state = adpcm.new_state(predictor, index)
        adpcm.decode_into(blob, 8, nibs, out, 1, state)
    return [out[2 * i] for i in range(n_samples)]


def _le16(raw, i):
    v = raw[2 * i] | (raw[2 * i + 1] << 8)
    return v - 65536 if v > 32767 else v


def _first_diff(raw, got, n):
    for i in range(n):
        if _le16(raw, i) != got[i]:
            return "%d: %d vs %d" % (i, got[i], _le16(raw, i))
    return "none"


# --- (b) throughput --------------------------------------------------------

def check_throughput():
    section("b", "decode throughput against the 16 kHz the DMA drains at")
    try:
        import adpcm
    except ImportError as exc:
        print("   skipped: %s" % exc)
        return
    gc.collect()
    n = 16000
    src = bytearray(n // 2)
    for i in range(len(src)):
        # Codes that keep the step index climbing, so the loop takes its
        # longest path rather than the cheap `diff = step >> 3` one.
        src[i] = 0x77
    out = array("h", bytes(4 * n))
    state = adpcm.new_state(0, 0)
    t0 = time.ticks_us()
    adpcm.decode_into(src, 0, n, out, 0, state)
    dt = time.ticks_diff(time.ticks_us(), t0)
    rate = n * 1_000_000 // max(dt, 1)
    print("   %d samples in %d us = %d samples/s" % (n, dt, rate))
    print("   one 12000-word half costs %d ms; the DMA takes 750 ms to drain it"
          % (12000 * dt // n // 1000))
    note(rate > 4 * 16000, "at least 4x real time",
         "%d samples/s against 16000 needed" % rate)
    del out, src


# --- (c) the re-arm gap ----------------------------------------------------

def check_stream(i2c):
    section("c", "DMA re-arm gap while streaming a real clip")
    try:
        import adpcm  # noqa: F401
        import listen
    except ImportError as exc:
        print("   skipped: %s" % exc)
        return None, None

    gc.collect()
    recorder = listen.Recorder()
    if not recorder.bind_voice():
        print("   skipped: no usable voice.pak on this board")
        return recorder, None
    clip = _first_clip(recorder)
    if clip is None:
        print("   skipped: voice.pak has no clips")
        return recorder, None

    ok = recorder.speak(i2c, clip)
    note(ok, "a clip streamed to the end")
    print("   %d boundaries, widest gap %d us"
          % (recorder.play_boundaries, recorder.play_gap_us))
    # The FIFO is 8 words deep with JOIN_TX, which is 8 samples = 500 us at
    # 16 kHz. Inside that, the PIO never runs dry and the join is inaudible;
    # past it, DOUT holds its last level and there is a tick at the boundary.
    if recorder.play_boundaries == 0:
        print("   (the clip fitted one half -- no boundary was crossed)")
    else:
        note(recorder.play_gap_us < 500, "the gap fits inside the TX FIFO",
             "%d us against ~500 us of FIFO" % recorder.play_gap_us)
    print("   note: this is an UPPER bound. It is measured from when the poll")
    print("   NOTICED the DMA finish, which is up to one poll iteration late.")
    return recorder, clip


def _first_clip(recorder):
    """The id of the first clip in the pak, read straight off the index."""
    pak = recorder._pak
    if pak is None or pak.count == 0:
        return None
    entry = bytearray(adpcm_entry_len())
    pak._fh.seek(16)
    if pak._fh.readinto(entry) != len(entry):
        return None
    return bytes(entry[0:8])


def adpcm_entry_len():
    import adpcm
    return adpcm.ENTRY_LEN


# --- (d) the ear -----------------------------------------------------------
#
# Not here on purpose. See the docstring: it needs a person listening at the
# moment it happens, which is a different act from reading a log, and it is
# the only check in this file whose result says anything about sound.


# --- main ------------------------------------------------------------------

def main():
    print("voice_probe: ADPCM decode and streaming playback")
    print("MicroPython %s" % (sys.implementation,))
    gc.collect()
    print("free heap at start: %d bytes" % gc.mem_free())

    check_fixtures()
    check_throughput()

    recorder = clip = None
    try:
        import board
        i2c = board.bus()
    except Exception as exc:  # noqa: BLE001
        print("\nno I2C bus (%s: %s) -- skipping (c) and (d)"
              % (type(exc).__name__, exc))
        i2c = None
    if i2c is not None:
        recorder, clip = check_stream(i2c)

    print()
    if FAILED:
        print("FAILED (%d):" % len(FAILED))
        for name in FAILED:
            print("  - %s" % name)
    else:
        print("all automated checks passed. None of them is (d): they prove")
        print("the arithmetic and the timing, not that a speaker moved.")
        print("Run (d) with someone listening -- see the docstring.")


main()
